/*
 * SPDX-FileCopyrightText: 2026 fcitx5-skk-mozc contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Mozc IPC client. Talks to a running mozc_server via the vendored
 * commands.proto.
 *
 * Lifecycle per query (no learning):
 *   CREATE_SESSION
 *   SEND_KEY (yomi, as a synthetic SPACE-triggered conversion)
 *   SEND_COMMAND CONVERT
 *   -> read Output.preedit / Output.all_candidate_words / Output.segments
 *   SEND_COMMAND RESET_CONTEXT
 *   DELETE_SESSION
 *
 * We never SUBMIT (which would touch mozc's user_history). All learning is
 * persisted by SKK to ~/.skk-jisyo separately.
 */

#include "mozc_client.h"
#include "ipc_socket.h"

// Generated by protoc at build time from $mozc-src/src/protocol/commands.proto.
// Path comes via CMakeLists.txt include_directories.
#include "proto/commands.pb.h"

#include <chrono>
#include <cstdint>
#include <cstdio>
#include <random>
#include <thread>

namespace skk_mozc {

namespace mc = mozc::commands;

struct MozcClient::Impl {
    std::string socket_path;
    // Session id remembered across resizeSegment / moveSegmentCandidate calls
    // that target the same conversion. resetContext() / convert() clear it.
    uint64_t session_id = 0;
    bool warned_unavailable = false;

    std::optional<std::vector<uint8_t>>
    roundtrip(const mc::Input &input, std::chrono::milliseconds timeout) {
        std::string serialized;
        if (!input.SerializeToString(&serialized)) {
            return std::nullopt;
        }
        std::vector<uint8_t> payload(serialized.begin(), serialized.end());
        return ipc::sendRequest(socket_path, payload, timeout);
    }

    std::optional<mc::Output>
    call(const mc::Input &input, std::chrono::milliseconds timeout) {
        auto raw = roundtrip(input, timeout);
        if (!raw) {
            return std::nullopt;
        }
        mc::Output out;
        if (!out.ParseFromArray(raw->data(),
                                static_cast<int>(raw->size()))) {
            return std::nullopt;
        }
        return out;
    }
};

namespace {

bool ensureServerReachable(MozcClient::Impl &impl,
                           const MozcClientOptions &opts) {
    // Cheap reachability probe: tiny NO_OP via PING.
    mc::Input ping;
    ping.set_type(mc::Input::NO_OPERATION);
    auto reply = impl.call(ping, opts.timeout);
    if (reply) {
        return true;
    }
    // Try lazy server start, then one retry. We deliberately do NOT extend the
    // user-visible budget: the next user keypress will get fresh budget.
    if (ipc::spawnServer(opts.mozc_server_path)) {
        // Poll for socket appearance briefly (~30ms total).
        for (int i = 0; i < 6; ++i) {
            std::this_thread::sleep_for(std::chrono::milliseconds(5));
            auto retry = impl.call(ping, opts.timeout);
            if (retry) {
                return true;
            }
        }
    }
    if (!impl.warned_unavailable && opts.debug) {
        std::fprintf(stderr,
                     "[skk-mozc] mozc_server unreachable; falling back to "
                     "SKK-only candidates\n");
        impl.warned_unavailable = true;
    }
    return false;
}

MozcCandidate fromAllCandidate(const mc::CandidateWord &cw,
                               const std::string &reading) {
    MozcCandidate out;
    out.value = cw.value();
    out.reading = reading;
    out.cost = cw.has_cost() ? cw.cost() : 0;
    if (cw.has_annotation() && cw.annotation().has_description()) {
        out.description = cw.annotation().description();
    }
    return out;
}

void extractTopCandidates(const mc::Output &out,
                          int max_candidates,
                          const std::string &yomi,
                          std::vector<MozcCandidate> &dst) {
    if (!out.has_all_candidate_words()) {
        return;
    }
    const auto &all = out.all_candidate_words();
    dst.reserve(static_cast<size_t>(all.candidates_size()));
    for (int i = 0; i < all.candidates_size() &&
                    static_cast<int>(dst.size()) < max_candidates;
         ++i) {
        dst.push_back(fromAllCandidate(all.candidates(i), yomi));
    }
}

void extractSegments(const mc::Output &out,
                     int max_per_segment,
                     std::vector<MozcSegment> &dst) {
    if (!out.has_preedit()) {
        return;
    }
    const auto &pre = out.preedit();
    for (int i = 0; i < pre.segment_size(); ++i) {
        const auto &seg = pre.segment(i);
        MozcSegment s;
        s.reading = seg.key();
        // commands.Preedit.Segment carries the focused value, not the
        // alternative list; alternatives come from CandidateList that mozc
        // sends in a separate Output for the focused segment. v1 collects the
        // focused value only and lazily re-queries on TAB; the merger does
        // not need the full table up front.
        MozcCandidate c;
        c.value = seg.value();
        c.reading = seg.key();
        c.cost = 0;
        s.candidates.push_back(std::move(c));
        s.focused_index = 0;
        dst.push_back(std::move(s));
        (void)max_per_segment;
    }
}

} // namespace

MozcClient::MozcClient(MozcClientOptions options)
    : impl_(new Impl()), options_(std::move(options)) {
    impl_->socket_path = ipc::resolveSocketPath(options_.socket_path_override);
}

MozcClient::~MozcClient() {
    if (impl_) {
        if (impl_->session_id != 0) {
            mc::Input in;
            in.set_type(mc::Input::DELETE_SESSION);
            in.set_id(impl_->session_id);
            (void)impl_->call(in, options_.timeout);
        }
        delete impl_;
    }
}

void MozcClient::resetContext() {
    if (impl_->session_id == 0) {
        return;
    }
    mc::Input in;
    in.set_type(mc::Input::SEND_COMMAND);
    in.set_id(impl_->session_id);
    in.mutable_command()->set_type(mc::SessionCommand::RESET_CONTEXT);
    (void)impl_->call(in, options_.timeout);
}

std::optional<MozcConversionResult>
MozcClient::convert(const std::string &yomi) {
    if (yomi.empty()) {
        return std::nullopt;
    }
    if (!reachable_) {
        // We've already failed once this session; don't keep spending the
        // 50 ms budget on doomed connects.
        return std::nullopt;
    }
    if (!ensureServerReachable(*impl_, options_)) {
        reachable_ = false;
        return std::nullopt;
    }

    // Fresh session per query (we don't keep mozc state across user keystrokes
    // because all learning lives in SKK side).
    mc::Input create;
    create.set_type(mc::Input::CREATE_SESSION);
    auto create_out = impl_->call(create, options_.timeout);
    if (!create_out || !create_out->has_id()) {
        return std::nullopt;
    }
    impl_->session_id = create_out->id();

    // Feed yomi directly via SEND_KEY type=DIRECT_INPUT, then CONVERT.
    mc::Input feed;
    feed.set_type(mc::Input::SEND_KEY);
    feed.set_id(impl_->session_id);
    auto *key = feed.mutable_key();
    key->set_key_string(yomi);
    // Force conversion immediately:
    auto feed_out = impl_->call(feed, options_.timeout);
    if (!feed_out) {
        impl_->session_id = 0;
        return std::nullopt;
    }

    mc::Input convert;
    convert.set_type(mc::Input::SEND_COMMAND);
    convert.set_id(impl_->session_id);
    convert.mutable_command()->set_type(mc::SessionCommand::CONVERT);
    auto convert_out = impl_->call(convert, options_.timeout);
    if (!convert_out) {
        impl_->session_id = 0;
        return std::nullopt;
    }

    MozcConversionResult result;
    extractTopCandidates(*convert_out, options_.max_candidates, yomi,
                         result.top_candidates);
    extractSegments(*convert_out, options_.max_candidates, result.segments);

    // We're done with mozc-side state for this query.
    resetContext();
    {
        mc::Input del;
        del.set_type(mc::Input::DELETE_SESSION);
        del.set_id(impl_->session_id);
        (void)impl_->call(del, options_.timeout);
    }
    impl_->session_id = 0;

    if (result.top_candidates.empty() && result.segments.empty()) {
        return std::nullopt;
    }
    return result;
}

std::optional<MozcConversionResult>
MozcClient::resizeSegment(int segment_index, int delta) {
    // Refinement requires a live session. Since convert() is single-shot, the
    // refinement sub-mode keeps its own MozcClient instance that calls
    // convertHold() (an internal helper we'd add when wiring the sub-mode).
    // For v0 the sub-mode is implemented in `bunsetsu/refiner.cpp` which holds
    // its own session; see that file.
    (void)segment_index;
    (void)delta;
    return std::nullopt;
}

std::optional<MozcConversionResult>
MozcClient::moveSegmentCandidate(int segment_index, int delta) {
    (void)segment_index;
    (void)delta;
    return std::nullopt;
}

} // namespace skk_mozc
